sudo: required

language: node_js

node_js:
  - "8"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm i -g npm
  - npm install -g @angular/cli
  - npm install
  - node_modules/protractor/bin/webdriver-manager update --versions.chrome 2.36

  - ng lint
  - ng test --code-coverage --watch false
  - ng e2e

  - ng build --prod --build-optimizer

after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
