sudo: required

notifications:
email: james.hn.sears@gmail.com

env:
  global:
    # travis encrypt COVERALLS_REPO_TOKEN=...
    - secure: "Spy1/amTNJ9wweOXpY/fpCm+bPovP6pK2Paby8RQd8qFYAY/pqnVwpu1D4eZ/ZsA5JA7NVe4UrXiEOnV51LSMj5DKgqu7SUFVKiUIwh3ZvLGXSmq7JNpLfjKVlfFow0I/QItD7uCo7AjYQ0Hg/Cs7EhI9L5hPTTAAmk2A7vEamIwOZU1m0Km+eW715+HKqD2Q4bfgSlK7vo8z1E/TjFtVFHA+sQdU8yi0/sKgwOh579tnD857zvO0HoxdTlamj3Cr6DT8f7JdnIULcFcoC81cy5DpujUWpgrkmc7lWtS0CcKJJ+TIADNN0bSG8MALc6jqG7CxpLcxEOwsFRe2t5slHe7S0f6ST+iihe7BVOyBv4MQQmK1OS+IF4aktkz62YfzSgTl+saVoJRo/vNGStN250IYfom+ePi8RODPtYfQwdCD1EqCsXgDSrodj7fLW+qhd+eqybxXfDAj3USvzhHjQmDVp6pFil2x+FDIDqW1y8rW5BaMuojowfKY0A1suu4k8TSvxSxyd+L0uI9xkr90b6XEJsK4BzofFmo/sR262s9JbJr3aAxEUHFJ1nwROaglefhAJCaie9iDTYdcthvKvNl+Iwj1+5WZQktOK8S4oCsXGwgjYZvCN1L2dk3Gjz/SzjpyHFv5TVdm1YZvAGMX3SHBhsx8kZYi0kz50lwbpw="
    # travis encrypt CODACY_PROJECT_TOKEN=...
    - secure: "CcW4zz5rJnlRGNJ+hmLjMftdU1011B9t0u1tJffPNZJnI9tNoDb0Hd4yTyiqj9VETU18uToOax5DR/RJKfgpwKORiVDpKk5ZI1CEYImdSsWcZTFG/EDqf4R/kG/13XtQLOtfbS9e429qloOy6YzYj8PkK2l695x0F+jnBtOE0On9nKQ3S/s9sy15+drkx+uzI2yc6ZdcsU3Gy3Xi3lUlAyLRAgGft7EWfhKzw2qPUh7VJvGzXK8pnSi6783F+3exKhrUzR4xYsSh4rj+aARuiMAh9cbY9Shz8pVZr/xflP5mw86e6FV5V9iCpm9a/6uuESpbW9uTJs6gp0uGWpilFhNwBzvTnlOn2ifqIs2HwqbhVBlYMtAJ5rHhqGyobm835kYl/9PDMlbfT/coXFJcMi5wQL5/PxOJwsw8Lagg3BLoWIVX7GeIb9z/llDv7c4AZaM2VXZ4tRP9fOz2Z47y8QW01T5sr3VM0VrzPXMjIf/PIKmBZfsmsK0w0Ue10vbRVGhQRw1VpJ5BOBMbYUsUbIMwJXAaknaLyoeCTmacou9KRVcVL3kEgbFInqEqnVJZxZEA4h+SlvTJLyXmZPEU9z++5gf24G95m+b5oulc9lDxzzqshPWCbm9iMLUgzEF+kbdCaVfM/6QWDdEK805l7D7J17bgNyq841JxCn8YX9E="

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "viPO0BdShvX5/DBqEafOGg2fMRyd836xLtH1KzXTYI5vZz8j//aywPMchrqFPAiHFcPlnto6YVP9/bMy14VVdzmAU3/cG/ra1dik+OP5XzIk8wsYbu3kOYX7Q9H3CV4y6TetJxkBSlzCaxVENkBAAHb3CGMqg6XN3c+cC3e9VPG7pvTFaAwyXq0mKoRuHPHRicbfrKQTdlyiqI5kDwmii/+6NI8vfMj6MXqfv0wIJC4uDG8nzjZ6ks0mq7AxB/7GdakjksunXWMp9NiJIg56hiT++gtkjVWDQ6cLERS/KVkWqezuGYMamc+wT5TQJxLYRzDF2c3KQsZqeSnLE0pCpxgRMzHvJlEE4uZfmhZWJEdMbbpjHDcbVpmnNV1yB7gHBG41u35Udw35WRTix4r6oRAFybYnRXWzoMSUpWEIBsSv0cLJp7eyIkQV/m6TqX6XFFyLhu+YF32ynmAYCUsAdWIfWIKfsqwhQdvGmdBMEU+3OHc7v5bmYaYY7zYuTPO2a4Nam7JZCd+/tqkEOqJga33V7lcYSUXkqXLEVBMj9QZup9B6ak1k0NiBxIV8P5U2C6Sj0MUwbP7guDD/8v9PotmnxAm6IwRlgfzhN5qr4P5D89WnN1+I330Yk5ZfFWzef6o06KaEwBDmbCWjyqrr/y8+jG/tGPEoz1BZ+qmoGIw="

git:
  depth: false

language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm install typescript@">=3.1.1 <3.2"

script:
  - node_modules/@angular/cli/bin/ng lint
  - node_modules/@angular/cli/bin/ng test --code-coverage --watch false
  # - node_modules/@angular/cli/bin/ng e2e

  - ls coverage
  - ls reports

  - node_modules/@angular/cli/bin/ng build --prod --build-optimizer

after_success:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
  - npm install codacy-coverage && cat ./coverage/lcov.info | codacy-coverage
  - sonar-scanner -X
 